spring:
  profiles:
    active: dev
  application:
    name: foodcatalogue-service
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 8082


